/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin/providers": {
    /** List providers */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    /**
     * Create provider (disabled)
     * @deprecated
     */
    post: {
      responses: {
        /** @description Not Implemented */
        501: {
          content: never;
        };
      };
    };
  };
  "/admin/providers/{id}/balance": {
    /** Get provider balance */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/admin/providers/{id}": {
    /**
     * Disable provider (disabled)
     * @deprecated
     */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Not Implemented */
        501: {
          content: never;
        };
      };
    };
    /**
     * Update provider (disabled)
     * @deprecated
     */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Not Implemented */
        501: {
          content: never;
        };
      };
    };
  };
  "/admin/providers/{id}/test": {
    /**
     * Test provider (disabled)
     * @deprecated
     */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Not Implemented */
        501: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
