openapi: 3.0.0
info:
  title: SMS Provider Admin API
  version: 1.0.0
paths:
  /admin/providers:
    get:
      summary: List providers
      responses:
        '200': { description: OK }
    post:
      summary: Create provider (disabled)
      deprecated: true
      responses:
        '501': { description: Not Implemented }
  /admin/providers/{id}/balance:
    get:
      summary: Get provider balance
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /admin/providers/{id}:
    patch:
      summary: Update provider (disabled)
      deprecated: true
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '501': { description: Not Implemented }
    delete:
      summary: Disable provider (disabled)
      deprecated: true
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '501': { description: Not Implemented }
  /admin/providers/{id}/test:
    post:
      summary: Test provider (disabled)
      deprecated: true
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '501': { description: Not Implemented }
