version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: sms_gateway_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend-server-b:
    image: server-b:v1.3
    restart: always
    environment:
      LISTEN_ADDR: ":8081"
      DATABASE_URL: "host=postgres user=user password=password dbname=sms_gateway_db port=5432 sslmode=disable TimeZone=Asia/Tehran"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      RABBITMQ_QUEUE_NAME: "sms_messages"
      DEFAULT_ADMIN_USERNAME: "admin"
      DEFAULT_ADMIN_PASSWORD: "password"
      JWT_SECRET_KEY: "your_super_secret_jwt_key" # IMPORTANT: Change this to a strong, random key in production!
      ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173" # Frontend URLs for CORS
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    image: frontend:v1.1
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend-server-b 
    environment:
      VITE_API_BASE_URL: "http://localhost:8081"

volumes:
  postgres_data:
  rabbitmq_data: