name: Go Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Test backend-server-a
        working-directory: sms-gateway-project/backend-server-a
        run: go test ./...
      - name: Test backend-server-b
        working-directory: sms-gateway-project/backend-server-b
        run: go test ./...
